# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `load_path`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, regardless of whether it is called explicitly or not.
# See http://rspec.info/features/3-12/rspec-core/command-line/

# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on every test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the files that actually need it.

# See http://rspec.info/features/3-12/rspec-core/configuration/
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.

  config.before(:each, type: :request) do
    Rails.application.reload_routes_unless_loaded
  end

  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the RSpec
    # examples/groups fail if there are any expectations defined outside the
    # example blocks or matched by the configured `on_error` callback.
    #
    # See http://rspec.info/features/3-12/rspec-core/configuration/
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library such as bogus or flexmock here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `true` in RSpec 4. It makes the RSpec
  # examples/groups fail if there are any expectations defined outside the
  # example blocks or matched by the configured `on_error` callback.
  config.define_derived_metadata do |meta|
    meta[:aggregate_failures] = true
  end

  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, etc. to simplify this syntax:
  #
  #     # This will run this single example:
  #     RSpec.describe UsersController, type: :controller do
  #       it "does something" do
  #         # ...
  #       end
  #     end
  #
  # The following line is provided for convenience purposes. It has nothing
  # to do with `rspec-rails`.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to optimize
  # the next run. This file will be created when the first test run happens
  # and will be deleted when the tests are re-run.
  # Learn more: https://rspec.info/features/3-12/rspec-core/features/example-ordering/
  #
  # For now we'll leave this disabled
  # config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more information, see:
  # https://rspec.info/features/3-12/rspec-core/configuration/
  #
  # Many RSpec users commonly either run the entire test suite or an
  # individual file, and it's rare to want to run an individual example by line
  # number. It's more useful to instead create a shared example group (see below)
  # to share common test logic, and avoid duplication. You can still run
  # individual examples by line number if you really want to.
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire test suite or an
  # individual file, and it's rare to want to run an individual example by line
  # number. It's more useful to instead create a shared example group (see below)
  # to share common test logic, and avoid duplication. You can still run
  # individual examples by line number if you really want to.
  #
  # See http://rspec.info/features/3-12/rspec-core/configuration/
  config.warnings = true

  # Use color in output.
  config.color = true

  # Use more verbose output format.
  config.formatter = :progress
end
